## Tensors & Operations

In [59]:
import torch

In [60]:
# 1-D tensor 
a = torch.tensor([4,5,9])
# 2-D tensor
b = torch.tensor([[3,4,7],
                  [9,8,3],
                  [1,9,7]])
a,b

(tensor([4, 5, 9]),
 tensor([[3, 4, 7],
         [9, 8, 3],
         [1, 9, 7]]))

In [61]:
# Shape is an attribute & size is a method 
print(a.shape,b.shape)
print(a.size(),b.size())

torch.Size([3]) torch.Size([3, 3])
torch.Size([3]) torch.Size([3, 3])


In [62]:
# In datatype Float & Double
c = torch.FloatTensor([[2,3,7,],
                       [9,4,2]])
d = torch.DoubleTensor([[2,5,6],
                        [2,8,7]])
print(c)
print(c.dtype)
print(d)
print(d.dtype)

tensor([[2., 3., 7.],
        [9., 4., 2.]])
torch.float32
tensor([[2., 5., 6.],
        [2., 8., 7.]], dtype=torch.float64)
torch.float64


In [63]:
print(c.mean(),d.std())

tensor(4.5000) tensor(2.5298, dtype=torch.float64)


### Note: If one of the dimensions is -1, its size can be inferred


In [64]:
# Reshaping 
print(b.view(-1,1))

#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
print(b.ndim)

tensor([[3],
        [4],
        [7],
        [9],
        [8],
        [3],
        [1],
        [9],
        [7]])
tensor([[3, 4, 7, 9, 8, 3, 1, 9, 7]])
torch.Size([1, 9])
2


In [65]:
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))



tensor([[[-0.0582,  0.0535,  0.3627, -0.4277],
         [-0.0846, -0.0111,  2.2198, -1.9308],
         [-0.5079, -1.7386, -0.1643, -1.1868]],

        [[ 1.6911,  0.7561,  0.0533,  1.6616],
         [ 0.0407,  1.9136,  0.8203,  1.5195],
         [ 0.2678, -2.3893, -1.3377, -1.6780]]])
tensor([[-0.0582,  0.0535,  0.3627, -0.4277, -0.0846, -0.0111,  2.2198, -1.9308,
         -0.5079, -1.7386, -0.1643, -1.1868],
        [ 1.6911,  0.7561,  0.0533,  1.6616,  0.0407,  1.9136,  0.8203,  1.5195,
          0.2678, -2.3893, -1.3377, -1.6780]])
tensor([[-0.0582,  0.0535,  0.3627, -0.4277, -0.0846, -0.0111,  2.2198, -1.9308,
         -0.5079, -1.7386, -0.1643, -1.1868],
        [ 1.6911,  0.7561,  0.0533,  1.6616,  0.0407,  1.9136,  0.8203,  1.5195,
          0.2678, -2.3893, -1.3377, -1.6780]])


In [66]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.9815, 0.8231, 0.3390, 0.6735],
        [0.7598, 0.8495, 0.7914, 0.9971],
        [0.0265, 0.8174, 0.0917, 0.2344],
        [0.8165, 0.6241, 0.1597, 0.7280]])


In [67]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[6, 9, 9],
        [7, 6, 8],
        [8, 6, 6]])


In [68]:
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

9


## Numpy Bridge

In [69]:
import numpy as np

In [70]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [71]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [72]:
#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    b = b.cuda()
    print(b)

False


In [73]:
#convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


## Tensor Concatenation


In [74]:
#Tensor Concatenation 
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print("Column wise \n",con_1)
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print("Row wise \n",con_2)


tensor([[ 1.5716,  0.5063,  0.6617, -0.9603, -0.2902],
        [-0.2833, -0.0279,  0.0421, -1.1027,  0.6615]])
tensor([[-0.1894, -1.9833, -0.4322, -0.5471,  0.3931],
        [ 0.9988, -0.3943,  0.9209,  0.3357,  0.3309],
        [ 1.9869, -0.9949, -0.5981, -1.2993,  0.5683]])
Column wise 
 tensor([[ 1.5716,  0.5063,  0.6617, -0.9603, -0.2902],
        [-0.2833, -0.0279,  0.0421, -1.1027,  0.6615],
        [-0.1894, -1.9833, -0.4322, -0.5471,  0.3931],
        [ 0.9988, -0.3943,  0.9209,  0.3357,  0.3309],
        [ 1.9869, -0.9949, -0.5981, -1.2993,  0.5683]])
tensor([[-0.5509,  0.3665, -0.3418],
        [ 0.6412, -0.6300,  0.7199]])
tensor([[-0.6898, -1.0626, -1.1346, -1.1015, -0.7110],
        [ 0.9937, -0.0343,  0.6548, -0.1246,  0.8475]])
Row wise 
 tensor([[-0.5509,  0.3665, -0.3418, -0.6898, -1.0626, -1.1346, -1.1015, -0.7110],
        [ 0.6412, -0.6300,  0.7199,  0.9937, -0.0343,  0.6548, -0.1246,  0.8475]])


## Adding Dimensions to Tensors

In [75]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)

tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)


tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


In [76]:
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[[0.8133, 0.4405, 0.7514, 0.9325],
         [0.8841, 0.4036, 0.8466, 0.3881],
         [0.6634, 0.9110, 0.5517, 0.1515]],

        [[0.5319, 0.5188, 0.5907, 0.9542],
         [0.1358, 0.8207, 0.0759, 0.8190],
         [0.6612, 0.2079, 0.5134, 0.2246]]])


tensor([[0.7514, 0.8466, 0.5517],
        [0.5907, 0.0759, 0.5134]])
torch.Size([2, 3])


tensor([[[0.7514],
         [0.8466],
         [0.5517]],

        [[0.5907],
         [0.0759],
         [0.5134]]])
torch.Size([2, 3, 1])


## AutoGrad

##### If requires_grad=True, the Tensor object keeps track of how it was created.

In [77]:
a = torch.tensor([3.,4.,5.],requires_grad=True)
b = torch.tensor([7.,3.,9.],requires_grad=True)
# a and b have their required_grad set to true, therefore we an compute gradients with respect to them
z = a + b
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([10.,  7., 14.], grad_fn=<AddBackward0>)
tensor(31., grad_fn=<SumBackward0>)


In [78]:
#Now if we backpropagate on s, we can find the gradients of s with respect to a
s.backward()
print(a.grad)

tensor([1., 1., 1.])


In [79]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)

False False
None


In [80]:
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y


True


In [81]:
new_z = z.detach()
print("new_z : ",new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

new_z :  None
True
True
False


In [82]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
