## Tensors & Operations

In [2]:
import torch

In [15]:
# 1-D tensor 
a = torch.tensor([4,5,9])
# 2-D tensor
b = torch.tensor([[3,4,7],
                  [9,8,3],
                  [1,9,7]])
a,b

(tensor([4, 5, 9]),
 tensor([[3, 4, 7],
         [9, 8, 3],
         [1, 9, 7]]),
 1,
 <function Tensor.dim>)

In [4]:
# Shape is an attribute & size is a method 
print(a.shape,b.shape)
print(a.size(),b.size())

torch.Size([3]) torch.Size([3, 3])
torch.Size([3]) torch.Size([3, 3])


In [5]:
# In datatype Float & Double
c = torch.FloatTensor([[2,3,7,],
                       [9,4,2]])
d = torch.DoubleTensor([[2,5,6],
                        [2,8,7]])
print(c)
print(c.dtype)
print(d)
print(d.dtype)

tensor([[2., 3., 7.],
        [9., 4., 2.]])
torch.float32
tensor([[2., 5., 6.],
        [2., 8., 7.]], dtype=torch.float64)
torch.float64


In [6]:
print(c.mean(),d.std())

tensor(4.5000) tensor(2.5298, dtype=torch.float64)


### Note: If one of the dimensions is -1, its size can be inferred


In [14]:
# Reshaping 
print(b.view(-1,1))

#Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)
print(b.ndim)

tensor([[3],
        [4],
        [7],
        [9],
        [8],
        [3],
        [1],
        [9],
        [7]])
tensor([[3, 4, 7, 9, 8, 3, 1, 9, 7]])
torch.Size([1, 9])
2


In [16]:
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channles,rows,columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))



tensor([[[-1.8433, -1.3058, -0.0469,  2.3978],
         [-0.7416, -0.4729, -0.0194, -0.3682],
         [ 1.2781, -0.6163,  0.3273, -0.4469]],

        [[-0.1188, -0.1055, -0.3077, -0.1975],
         [-0.0951,  0.3180,  1.0694,  0.4305],
         [ 0.4786, -1.5276,  0.3150, -1.1165]]])
tensor([[-1.8433, -1.3058, -0.0469,  2.3978, -0.7416, -0.4729, -0.0194, -0.3682,
          1.2781, -0.6163,  0.3273, -0.4469],
        [-0.1188, -0.1055, -0.3077, -0.1975, -0.0951,  0.3180,  1.0694,  0.4305,
          0.4786, -1.5276,  0.3150, -1.1165]])
tensor([[-1.8433, -1.3058, -0.0469,  2.3978, -0.7416, -0.4729, -0.0194, -0.3682,
          1.2781, -0.6163,  0.3273, -0.4469],
        [-0.1188, -0.1055, -0.3077, -0.1975, -0.0951,  0.3180,  1.0694,  0.4305,
          0.4786, -1.5276,  0.3150, -1.1165]])


In [17]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.6981, 0.1912, 0.4956, 0.2238],
        [0.1177, 0.9082, 0.1635, 0.3205],
        [0.9464, 0.9518, 0.8818, 0.0728],
        [0.1879, 0.7500, 0.1389, 0.2384]])


In [18]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[7, 8, 6],
        [9, 8, 8],
        [8, 6, 9]])


In [19]:
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

9


## Numpy Bridge